language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
install:
  - "pip install ."
  - "pip install coveralls"
before_script:
  - "pip install -r requirements.txt"
script: "coverage run --source=py-googletrans tests.py -v"
after_success: "coveralls"
